version: '2'
services:
  app:
    build: .
    command: ["-c", "/config/config.yml", "--global-config", "/config/testnet-global.config.json"]
    ports:
      - 30303:30303/udp
      - 3000:3000/tcp
    volumes:
      - data:/data
    restart: always
    mem_limit: 5G
  explorer:
    build:
      context: explorer
    restart: always
    ports:
      - 80:8080

volumes:
  data: